// Generates alphabetical index pages for the schema reference:
// src/constructor/index.md, src/method/index.md, src/type/index.md
// Run AFTER tools/extract.mjs.
import { readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';

const SRC = path.resolve('src');

function parseFm(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const fm = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (kv) fm[kv[1]] = kv[2].replace(/^"|"$/g, '');
  }
  return fm;
}

const KINDS = [
  ['constructor', 'Constructors', 'https://core.telegram.org/schema'],
  ['method', 'Methods', 'https://core.telegram.org/schema'],
  ['type', 'Types', 'https://core.telegram.org/schema'],
];

// Links are written absolute, from the site root: a document-relative one would
// depend on the index being served with a trailing slash, and it stays outside
// the reach of tools/verify.mjs' link check.
// Page names are not necessarily URL-safe either: `#` is the TL "nat" type and
// `Vector t` carries a space. Written verbatim, the first becomes the fragment
// link `#/` (which never leaves the index) and the second is not parsed as a
// link at all — markdown-it leaves `Vector t](Vector t/)` as literal text.
// Encoding per segment mirrors the `urlpath` filter in eleventy.config.mjs.
const linkPath = (kind, name) => `/${kind}/${encodeURIComponent(name)}/`;

// `/type/#` was never saved upstream, so its front matter says "Page not found".
// That is the title of the page, not the name of a type: the index must still
// list it as `#`, otherwise the entry reads as a broken link to the reader.
const label = (fm, name) => (fm.title && fm.title !== 'Page not found' ? fm.title : name);

for (const [kind, title, original] of KINDS) {
  const dir = path.join(SRC, kind);
  const files = (await readdir(dir)).filter((f) => f.endsWith('.md') && f !== 'index.md').sort((a, b) => a.localeCompare(b));
  const lines = [
    '---',
    `title: "${title} — TL schema reference"`,
    `original: "${original}"`,
    'section: schema',
    // rendered by layout.njk as the "generated by the mirror" note
    'generated: true',
    'layout: layout.njk',
    '---',
    '',
    `# ${title}`,
    '',
    `All ${kind}s of the TL schema (${files.length}). Names link to pages with the full definition, parameters and description.`,
    '',
  ];
  for (const f of files) {
    const fm = parseFm(await readFile(path.join(dir, f), 'utf8'));
    const name = f.replace(/\.md$/, '');
    lines.push(`- [${label(fm, name)}](${linkPath(kind, name)})`);
  }
  await writeFile(path.join(dir, 'index.md'), lines.join('\n') + '\n');
  console.log(kind, 'index:', files.length);
}
